// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdVPSqcU2uZfuXvDIFInRvYB1_yEwIO_4',
    appId: '1:929601953173:web:3a3f8c557d4887e006aa9c',
    messagingSenderId: '929601953173',
    projectId: 'courthub-app',
    authDomain: 'courthub-app.firebaseapp.com',
    storageBucket: 'courthub-app.firebasestorage.app',
    measurementId: 'G-BFF7GG2JS6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxOga1vbU53c5SuJ7SDuXbPHVKAzOMpUw',
    appId: '1:929601953173:android:eb4450bb28b6827e06aa9c',
    messagingSenderId: '929601953173',
    projectId: 'courthub-app',
    storageBucket: 'courthub-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLdw1_CeufV5PgQyOrSxkJm4d2oaXCyQ0',
    appId: '1:929601953173:ios:8adfe01e8f951cbc06aa9c',
    messagingSenderId: '929601953173',
    projectId: 'courthub-app',
    storageBucket: 'courthub-app.firebasestorage.app',
    iosBundleId: 'com.mycompany.CounterApp',
  );

}