name: Run Balanced Backfill (cap=40,000)

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      # Use your existing deploy key secret as the Firebase token
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_DEPLOY_KEY }}
      PROJECT_ID: courthub-app
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Validate required secrets and variables
        shell: bash
        run: |
          set -euo pipefail
          if [[ -z "${FIREBASE_TOKEN:-}" ]]; then
            echo "FIREBASE_TOKEN is NOT set. Please add FIREBASE_DEPLOY_KEY in repo secrets." >&2
            exit 1
          fi
          echo "FIREBASE_TOKEN is set (value hidden)."
          echo "PROJECT_ID=$PROJECT_ID"

      - name: Verify firebase-tools version (v13)
        run: npx -y firebase-tools@13 --version

      - name: Call runParksBackfillOnce (balanced)
        run: |
          set -euo pipefail
          echo '{"mode":"balanced","capPerRun":40000}' \
            | npx -y firebase-tools@13 \
                --project "$PROJECT_ID" \
                functions:call runParksBackfillOnce

      - name: Link to Firebase Console logs
        run: |
          echo "Logs: https://console.firebase.google.com/project/${PROJECT_ID}/functions/details;tab=logs?region=us-central1&functionId=runParksBackfillOnce"
