name: Run Balanced Backfill (cap=40,000)

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Verify Firebase CLI version (npx pinned)
        run: |
          npx -y firebase-tools@12.9.1 --version

      - name: Call runParksBackfillOnce (Balanced, cap=40,000)
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_DEPLOY_KEY }}
        run: |
          set -euo pipefail
          echo "Invoking runParksBackfillOnce with mode=balanced, capPerRun=40000"
          npx -y firebase-tools@12.9.1 --project courthub-app functions:call runParksBackfillOnce --data '{"mode":"balanced","capPerRun":40000}'

      - name: Link to Firebase Console logs
        run: |
          echo "Logs: https://console.firebase.google.com/project/courthub-app/functions/details;tab=logs?region=us-central1&functionId=runParksBackfillOnce"
