name: Run Parks Backfill (Balanced one-time)

on:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

concurrency:
  group: backfill-balanced-run
  cancel-in-progress: false

jobs:
  run_balanced_once:
    name: Run Balanced Backfill (cap=40,000)
    runs-on: ubuntu-latest
    # Set your default Firebase project ID here or use GitHub Environments/Repository Variables
    env:
      TARGET_PROJECT: courthub-app
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          # Create a Service Account with permissions to call Firebase Functions
          # and store its JSON key in the repo secret FIREBASE_DEPLOY_KEY
          credentials_json: ${{ secrets.FIREBASE_DEPLOY_KEY }}

      - name: Install Firebase CLI
        # Pin to v12.x because newer CLIs removed/changed functions:call flags
        run: npm install -g firebase-tools@12.9.1

      - name: Call runParksBackfillOnce (Balanced, cap=40,000)
        run: |
          set -e
          echo "Invoking runParksBackfillOnce with mode=balanced, capPerRun=40000"
          firebase --project "${TARGET_PROJECT}" functions:call runParksBackfillOnce --data '{
            "mode": "balanced",
            "capPerRun": 40000,
            "clusterDecimals": 3,
            "parseCityStateNoApi": true,
            "refineNamesCap": 0,
            "pageSize": 600
          }'

      - name: Link to Firebase Console logs
        if: ${{ always() }}
        run: |
          echo "::notice::Open Functions logs: https://console.firebase.google.com/project/${{ env.TARGET_PROJECT }}/functions/list"
